CONFIG_LOG=y
CONFIG_SHELL=y
CONFIG_CPP=y

# DMA and UART async
CONFIG_DMA=y
CONFIG_UART_ASYNC_API=y

# Enable kernel features needed by async UART
CONFIG_TIMESLICING=y

# DAC and timer counter support for TIM6-triggered waveform output
CONFIG_DAC=y
CONFIG_COUNTER=y
